export const writers = [
    "Alex Zhao",
    "Andrew Guan",
    "Andy Yan",
    "Arman Ayazi",
    "Ashley Zhang",
    "Batir Yakhshilikov",
    "Bill Qian",
    "Chris Wang",
    "Clare Gu",
    "David Wang",
    "Edison Gao",
    "Edward Ye",
    "Eric Xie",
    "Eva Wu",
    "Evan Zhang",
    "Gabe Phillips",
    "Gloria Jin",
    "Henry Lu",
    "Jeffrey Boman",
    "Julian Kovalovsky",
    "Kevin Feng",
    "Kevin Shen",
    "Kiana",
    "Kiran Oliver",
    "Lewis Lau",
    "Liam Bryce",
    "Lucas Zeng",
    "Malinda Zhu",
    "Roy Brauwerman",
    "Ruixi Zhang",
    "Sam Easaw",
    "Shafi Bhaiyan",
    "Shaun Wang",
    "Shiven Khurana",
    "Somil Varshney",
    "Tane Park",
    "Tobias Lin",
    "Tony",
    "Will Roe",
];

export const staff = [
    ["Kele Zhang", "Reanna Jin", "Ashley Zhang", "Alex Zhao"],
    ["Justin Jiang", "Jessica Hsieh", "Manil Singh-Prasad", "Sam Easaw"],
];
